[package]
name = "move_character"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0-rc.3"
bevy_ecs_tilemap = { version = "0.16.0-rc.1", features = ["render"] }
thiserror = "2.0.12"
tiled = "0.14.0"
