[package]
name = "move_character"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15"
bevy_ecs_tilemap = "0.15"
bevy_ecs_tiled = { version = "0.6", features = ["avian"] }
avian2d = "0.2.1"
